export const ROLE_PERMISSIONS: Record<string, Record<string, boolean>> = {
  'Administrator': {
    reports: true,
    drivers: true,
    vehicles: true,
    locations: true,
    new_job: true,
    dashboard: true,
    calendar: true,
    all_jobs: true,
    history: true,
    admins: true,
    line_settings: true,
    system_settings: true,
  },
  'Admin': {
    reports: true,
    drivers: true,
    vehicles: true,
    locations: true,
    new_job: true,
    dashboard: true,
    calendar: true,
    all_jobs: true,
    history: true,
    admins: true,
    line_settings: true,
    system_settings: true,
  },
  'Driver': {
    reports: false,
    drivers: false,
    vehicles: true,
    locations: false,
    new_job: false,
    dashboard: true,
    calendar: true,
    all_jobs: true,
    history: true,
    admins: false,
    line_settings: false,
    system_settings: false,
  }
};
